### PR TITLE
Implemented routing in application

### LINKED ISSUE #6: Implement Routing in the Application
Implement Router DOM along with its types.

### PR DESCRIPTION
**Pull request by raghavdhingra**

### CODE REVIEW

**Review by shivaylamba — CHANGES_REQUESTED** [review]
Please remove keyword any and specify the type of component in route.ts

**Comment by raghavdhingra** [comment]
@shivaylamba updated the type for component

**Review by shivaylamba — APPROVED** [review]
LGTM, thanks @raghavdhingra

**Comment by shivaylamba** [comment]
#6 closed

**Pull request merged**
